Repository apache/openwhisk, pull requests merged in 2018-06, with the labels that each got.

#3719 Fix attachment name compatibility issue
  common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
  tests/src/test/scala/whisk/core/database/test/AttachmentCompatibilityTests.scala
Labels: bug

#3717 Update Travis to use ASF-Release.cfg.
  tools/travis/scan.sh
Labels: apache, review

#3697 Add equals method to ensure that ByteSize instances satisfy Comparable contract
  common/scala/src/main/scala/whisk/core/entity/Size.scala
  tests/src/test/scala/whisk/core/entity/test/SizeTests.scala
Labels: review

#3720 Update the document regarding Open JDK and Oracle JDK
  README.md
  tools/macos/README.md
  tools/ubuntu-setup/README.md
  tools/ubuntu-setup/all.sh
  tools/ubuntu-setup/java8.sh
  tools/vagrant/Vagrantfile
Labels: apache, build, compliance, review

#3709 Inlined attachments
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/core/database/ArtifactStore.scala
  common/scala/src/main/scala/whisk/core/database/AttachmentInliner.scala
  common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
  common/scala/src/main/scala/whisk/core/database/CouchDbStoreProvider.scala
  common/scala/src/main/scala/whisk/core/database/DocumentFactory.scala
  common/scala/src/main/scala/whisk/core/database/memory/MemoryArtifactStore.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
  tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/whisk/core/database/test/AttachmentInlinerTests.scala
  tests/src/test/scala/whisk/core/database/test/AttachmentTests.scala
  tests/src/test/scala/whisk/core/database/test/DbUtils.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreAttachmentBehaviors.scala
Labels: artifactstore, reviewed

#3707 enable concurrent runs on ActionContainer test utility
  common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala
  tests/src/test/scala/actionContainers/ActionContainer.scala
Labels: review, testing

#3486 Check zookeeper (not log) to see that kafka's running
  ansible/roles/kafka/tasks/deploy.yml
Labels: deployment, review

#3740 Exclude logback-test.xml from test sources jar
  build.gradle
Labels: review, testing

#3748 Mention Slack and mailing list links in issue template
  .github/ISSUE_TEMPLATE.md
Labels: documentation

#3568 Add activation result integration test
  tests/src/test/scala/system/basic/WskActivationTests.scala
Labels: testing

#3761 Revert "Mitigate missing docker 1.12 binary download. (#3758)" as the cli is downloadbale again.
  core/invoker/Dockerfile
Labels: review

#3515 Introduce separate Akka dispatchers for CouchDB and Kafka Clients (#2954)
  common/scala/src/main/resources/reference.conf
  common/scala/src/main/scala/whisk/core/connector/MessageConsumer.scala
  common/scala/src/main/scala/whisk/core/database/CouchDbRestClient.scala
  common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
  common/scala/src/main/scala/whisk/core/database/RemoteCacheInvalidation.scala
Labels: review

#3619 Provide an activation store SPI
  common/scala/src/main/resources/reference.conf
  common/scala/src/main/scala/whisk/core/entity/ActivationId.scala
  common/scala/src/main/scala/whisk/core/entity/ActivationStore.scala
  common/scala/src/main/scala/whisk/core/entity/ArtifactActivationStore.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala
  core/controller/src/main/scala/whisk/core/controller/Actions.scala
  core/controller/src/main/scala/whisk/core/controller/Activations.scala
  core/controller/src/main/scala/whisk/core/controller/Controller.scala
  core/controller/src/main/scala/whisk/core/controller/Triggers.scala
  core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
  core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
  tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala
Labels: review

#3756 Report metrics of kafka's queue time.
  common/scala/src/main/scala/whisk/common/Logging.scala
  common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
Labels: review

#3753 Retry `ensureTopic` on transient, retriable exceptions.
  common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
Labels: review

#3773 Remove IBM Cloud reference from README.
  docs/README.md
Labels: apache, compliance

#3775 Remove unnecessary pause in retry method
  common/scala/src/main/scala/whisk/utils/Retry.scala
Labels: review

#3416 Refactor and unit test PoolingRestClient
  common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchRestClient.scala
  common/scala/src/main/scala/whisk/core/database/CloudantRestClient.scala
  common/scala/src/main/scala/whisk/core/database/CouchDbRestClient.scala
  common/scala/src/main/scala/whisk/http/PoolingRestClient.scala
  tests/src/test/scala/whisk/core/database/test/ExtendedCouchDbRestClient.scala
  tests/src/test/scala/whisk/http/PoolingRestClientTests.scala
Labels: review

#3776 Allow command runner to retry on network exit with custom retry
  common/scala/src/main/scala/whisk/utils/Retry.scala
  tests/src/test/scala/common/TestUtils.java
  tests/src/test/scala/common/Wsk.scala
Labels: review, testing

#3751 Allow invoker pools to overlap for small N.
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: loadbalancer, review

#3680 Adjust invoker playbook to pull docker images when a prefix and tag is specified.
  ansible/files/runtimes.json
  ansible/group_vars/all
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/entity/ExecManifest.scala
  common/scala/src/main/scala/whisk/core/mesos/MesosContainerFactory.scala
  core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  tests/src/test/scala/whisk/core/WhiskConfigTests.scala
  tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
  tests/src/test/scala/whisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
  tests/src/test/scala/whisk/core/entity/test/ExecManifestTests.scala
Labels: deployment, invoker, pgapproved

#3780 Only send kafka offset metrics, if offsets are meaningful.
  common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
Labels: kafka, review

#3782 Make test-instances of Exec depend on the loaded manifest.
  tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala
Labels: review, testing

#3745 Remove runtime builds
  .gitignore
  .travis.yml
  actionRuntimes/actionProxy/Dockerfile
  actionRuntimes/actionProxy/build.gradle
  actionRuntimes/javaAction/Dockerfile
  actionRuntimes/javaAction/build.gradle
  actionRuntimes/javaAction/delete-build-run.sh
  actionRuntimes/nodejs6Action/build.gradle
  actionRuntimes/nodejs8Action/Dockerfile
  actionRuntimes/nodejs8Action/build.gradle
  actionRuntimes/php7.1Action/Dockerfile
  actionRuntimes/php7.1Action/build.gradle
  actionRuntimes/python2Action/Dockerfile
  actionRuntimes/python2Action/build.gradle
  actionRuntimes/pythonAction/Dockerfile
  actionRuntimes/pythonAction/build.gradle
  actionRuntimes/swift3.1.1Action/Dockerfile
  actionRuntimes/swift3.1.1Action/build.gradle
  actionRuntimes/swift4.1Action/Dockerfile
  actionRuntimes/swift4.1Action/build.gradle
  sdk/docker/Dockerfile
  sdk/docker/build.gradle
  settings.gradle
  tests/build.gradle
  tests/dat/blackbox/badaction/Dockerfile
  tests/dat/blackbox/badaction/README.md
  tests/dat/blackbox/badaction/build.gradle
  tests/dat/blackbox/badaction/runner.py
  tests/dat/blackbox/badproxy/Dockerfile
  tests/dat/blackbox/badproxy/README.md
  tests/dat/blackbox/badproxy/build.gradle
  tools/actionProxy/Dockerfile
  tools/actionProxy/README.md
  tools/actionProxy/invoke.py
  tools/build/README.md
  tools/build/redo
Labels: deployment, review

#3617 Move version information to pureconfig and remove `whisk_version_name`.
  ansible/environments/distributed/group_vars/all
  ansible/environments/docker-machine/group_vars/all
  ansible/environments/local/group_vars/all
  ansible/environments/vagrant/group_vars/all
  ansible/group_vars/all
  ansible/logs.yml
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  ansible/templates/whisk.properties.j2
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
  tests/src/test/scala/actionContainers/ActionContainer.scala
Labels: review

#3802 Bump gradle and scoverage version, adjust scoverage plumbing.
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  tests/build.gradle
Labels: build, review

#3801 add a doc for securing actions
  docs/actions.md
  docs/security.md
Labels: documentation, review, security

#3507 allow use of string for controller id
  common/scala/src/main/scala/whisk/common/Logging.scala
  common/scala/src/main/scala/whisk/core/connector/Message.scala
  common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala
  common/scala/src/main/scala/whisk/core/database/RemoteCacheInvalidation.scala
  common/scala/src/main/scala/whisk/core/entity/InstanceId.scala
  common/scala/src/main/scala/whisk/core/mesos/MesosContainerFactory.scala
  core/controller/src/main/scala/whisk/core/controller/Controller.scala
  core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
  core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
  core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
  core/controller/src/main/scala/whisk/core/entitlement/LocalEntitlement.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancer.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
  core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  tests/src/test/scala/whisk/core/connector/tests/CompletionMessageTests.scala
  tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
  tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
  tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
  tests/src/test/scala/whisk/core/database/test/DbUtils.scala
  tests/src/test/scala/whisk/core/entity/test/ControllerInstanceIdTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: review

#3817 Generate whisk.conf as default config for wskadmin-next.
  .gitignore
  ansible/tasks/writeWhiskProperties.yml
  ansible/templates/whisk.conf.j2
  tools/admin/README-NEXT.md
  tools/admin/src/main/scala/whisk/core/cli/Main.scala
Labels: review, tooling

#3821 Avoid regenerating auth key multiple times
  tests/src/test/scala/whisk/core/database/UserCommandTests.scala
  tools/admin/src/main/scala/whisk/core/database/UserCommand.scala
Labels: review, tooling

#2282 Distributed tracing support #2192
  common/scala/build.gradle
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/common/TransactionId.scala
  common/scala/src/main/scala/whisk/common/tracing/OpenTracingProvider.scala
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/connector/Message.scala
  core/controller/src/main/resources/application.conf
  core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  tests/build.gradle
  tests/src/test/scala/common/WskTracingTests.scala
Labels: performance, reviewed, tooling

#3816 Reorganize actions doc.
  docs/actions-docker.md
  docs/actions-go.md
  docs/actions-java.md
  docs/actions-node.md
  docs/actions-php.md
  docs/actions-python.md
  docs/actions-swift.md
  docs/actions.md
  docs/reference.md
Labels: documentation, review

#3826 Don't use stubbed functions in InvokerSupervisionTests.
  tests/src/test/scala/common/LoggedFunction.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala
Labels: bug, heisenbug, review
