Repository apache/openwhisk, pull requests merged in 2018-10, with the labels that each got.

#4040 Prevent Artifact Store Polling for Large Activation Records
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
  common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/connector/MessagingProvider.scala
  common/scala/src/main/scala/whisk/core/entity/ActivationEntityLimit.scala
  core/controller/src/main/scala/whisk/core/controller/Controller.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala
Labels: ready

#4011 Customize invoker use memory for memory based loadbalancing
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/scala/whisk/core/entity/InstanceId.scala
  common/scala/src/main/scala/whisk/core/entity/Size.scala
  core/controller/src/main/resources/reference.conf
  core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  tests/src/test/scala/whisk/core/connector/tests/CompletionMessageTests.scala
  tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: invoker, review

#4048 Ensure that limits are set properly
  tests/src/test/scala/whisk/core/database/LimitsCommandTests.scala
  tools/admin/src/main/scala/whisk/core/database/LimitsCommand.scala
Labels: bug

#4071 Fix mock-verification in Container-tests.
  tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
Labels: review

#3950 Extend system testsuite
  core/controller/src/main/resources/apiv1swagger.json
  tests/dat/actions/argsPrint.js
  tests/dat/actions/runexception.js
  tests/src/test/scala/common/WskCliOperations.scala
  tests/src/test/scala/common/WskOperations.scala
  tests/src/test/scala/common/rest/WskRestOperations.scala
  tests/src/test/scala/system/basic/WskActionTests.scala
  tests/src/test/scala/whisk/core/cli/test/WskEntitlementTests.scala
  tests/src/test/scala/whisk/core/cli/test/WskRestBasicUsageTests.scala
  tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/PackagesApiTests.scala
Labels: ready, testing

#4041 Send active-ack after log collection for nonblocking activations.
  common/scala/src/main/scala/whisk/core/connector/Message.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  tests/src/test/scala/whisk/core/connector/tests/AcknowledgementMessageTests.scala
  tests/src/test/scala/whisk/core/connector/tests/CompletionMessageTests.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
Labels: feature request
