Repository apache/openwhisk, pull requests merged in 2018-09, with the labels that each got.

#3661 Restrict allowed namespaces when creating action of certain kinds
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/entity/Identity.scala
  common/scala/src/main/scala/whisk/http/ErrorResponse.scala
  core/controller/src/main/scala/whisk/core/controller/Actions.scala
  core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
  core/controller/src/main/scala/whisk/core/entitlement/KindRestrictor.scala
  tests/src/test/scala/whisk/core/controller/test/EntitlementProviderTests.scala
  tests/src/test/scala/whisk/core/controller/test/KindRestrictorTests.scala
Labels: controller, review

#4005 Allow updating auth key for user with wskadmin-next
  tests/src/test/scala/whisk/core/database/UserCommandTests.scala
  tools/admin/README-NEXT.md
  tools/admin/src/main/scala/whisk/core/database/UserCommand.scala
Labels: review, tooling

#3968 Secure the invoker with ssl.
  .gitignore
  ansible/README.md
  ansible/couchdb.yml
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  ansible/setup.yml
  common/scala/src/main/scala/whisk/common/Https.scala
  common/scala/src/main/scala/whisk/http/BasicHttpService.scala
  core/controller/src/main/scala/whisk/core/controller/Controller.scala
  core/controller/src/main/scala/whisk/core/controller/Triggers.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  tests/src/test/resources/application.conf.j2
  tools/vagrant/README.md
Labels: review

#3951 Docs fixes for action invocations
  docs/actions.md
Labels: documentation, review

#4030 Add additional debug information if activations have to wait in the invoker.
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
Labels: review

#4006 Adjust activation metric schema to reflect reality.
  common/scala/src/main/scala/whisk/core/connector/Message.scala
  common/scala/src/main/scala/whisk/core/entity/Parameter.scala
  core/controller/src/main/scala/whisk/core/controller/WebActions.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  docs/metrics.md
  tests/src/test/scala/whisk/core/connector/test/EventMessageTests.scala
  tests/src/test/scala/whisk/core/controller/test/ConductorsApiTests.scala
Labels: monitoring, review

#4019 Send activations of sequences to events topic.
  common/scala/src/main/scala/whisk/core/connector/Message.scala
  core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
  core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  tests/src/test/scala/whisk/common/UserEventTests.scala
Labels: review
