Repository apache/openwhisk, pull requests merged in 2018-11, with the labels that each got.

#4100 Always return activation without log on blocking invoke.
  core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
  tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
Labels: review

#3880 Modify that web action in the bound package can be accessed.
  core/controller/src/main/scala/whisk/core/controller/WebActions.scala
  docs/webactions.md
  tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Labels: controller, enhancement, ready, review

#4103 update from redis 3.2 to 4.0
  ansible/group_vars/all
Labels: apigw, companion

#4112 Create trigger activation only when active rule(s) are present
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/Triggers.scala
Labels: review

#4131 Send system overload metric from Controller
  common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
Labels: review

#4115 Ensure, that Result-ack is sent before Completion-ack.
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
Labels: review

#4136 Reduce invoker health action memory limit to 128MB
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala
Labels: review

#4122 Protect Package Bindings from containing circular references
  common/scala/src/main/scala/org/apache/openwhisk/http/ErrorResponse.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/Packages.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/entitlement/PackageCollection.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackagesApiTests.scala
Labels: bug, controller, ready, review
