Repository apache/openwhisk, pull requests merged in 2018-12, with the labels that each got.

#4108 Making Redis password protected
  ansible/group_vars/all
  ansible/roles/apigateway/tasks/deploy.yml
  ansible/roles/redis/tasks/deploy.yml
Labels: companion, pgapproved, redis

#4142 tools/dev - updated intellij script to start controller and invoker locally
  ansible/group_vars/all
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerClient.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainerFactory.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerForMacContainerFactory.scala
  tools/dev/README.md
  tools/dev/build.gradle
  tools/dev/src/main/groovy/intellijRunConfig.groovy
Labels: review

#4099 Cleanup/organize instructions for adding a new Action Runtime
  docs/actions-new.md
Labels: documentation, review

#4159 Add additional debug information to Loadbalancer.
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
Labels: review

#4172 .NET Core 2.2 Runtime
  ansible/files/runtimes.json
  core/controller/src/main/resources/apiv1swagger.json
  docs/actions-dotnet.md
  docs/actions.md
  tests/dat/actions/unicode.tests/dotnet-2.2.bin
  tests/dat/actions/unicode.tests/src/dotnet2.2/Apache.OpenWhisk.UnicodeTests.Dotnet/Apache.OpenWhisk.UnicodeTests.Dotnet.csproj
  tests/dat/actions/unicode.tests/src/dotnet2.2/Apache.OpenWhisk.UnicodeTests.Dotnet/Unicode.cs
  tests/dat/actions/unicode.tests/src/dotnet2.2/openwhisk-unicodetests-dotnet.sln
  tests/src/test/scala/system/basic/WskUnicodeTests.scala
Labels: enhancement, review, runtime
