Repository apache/openwhisk, pull requests merged in 2018-03, with the labels that each got.

#3338 implement suspend/resume for KubernetesContainer
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainer.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
  tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
  tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala
Labels: invoker, kubernetes, pgapproved, reviewed

#3343 Support time-series DB using Kamon Tag
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/scala/whisk/common/Logging.scala
  common/scala/src/main/scala/whisk/common/TransactionId.scala
  common/scala/src/main/scala/whisk/http/BasicHttpService.scala
  docs/metrics.md
  tests/src/test/scala/whisk/core/containerpool/docker/test/DockerClientTests.scala
  tests/src/test/scala/whisk/core/containerpool/docker/test/RuncClientTests.scala
Labels: pgapproved, reviewed

#3385 Remove test for included packages in python container.
  tests/src/test/scala/actionContainers/PythonActionContainerTests.scala
Labels: testing

#3364 Add retries to some entity "update" tests
  tests/src/test/scala/system/basic/WskBasicTests.scala
Labels: awaits-feedback, reviewed

#3302 Sanitize test subjects before tests.
  tests/src/test/scala/common/WskTestHelpers.scala
  tests/src/test/scala/limits/ThrottleTests.scala
Labels: review

#3379 Make action-time-limit's system bounds configurable.
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/entity/TimeLimit.scala
Labels: review

#3359 Change all empty collection creations to an explicit call to `empty`.
  common/scala/src/main/scala/whisk/common/Config.scala
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/LogDriverLogStore.scala
  common/scala/src/main/scala/whisk/core/entity/Parameter.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskPackage.scala
  core/controller/src/main/scala/whisk/core/controller/WebActions.scala
  core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
  core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
Labels: review

#3348 Allow wskadmin user block/unblock to accept a list of subject to block
  tests/src/test/scala/whisk/core/admin/WskAdminTests.scala
  tools/admin/wskadmin
Labels: reviewed

#3393 Turn off Kafka auto-commits.
  common/scala/src/main/resources/application.conf
Labels: kafka, review

#3362 Make ActivationId implementation leaner.
  common/scala/src/main/scala/whisk/core/entity/ActivationId.scala
  core/controller/src/main/scala/whisk/core/controller/Activations.scala
  tests/src/test/scala/whisk/core/connector/tests/CompletionMessageTests.scala
  tests/src/test/scala/whisk/core/containerpool/logging/SplunkLogStoreTests.scala
  tests/src/test/scala/whisk/core/containerpool/logging/test/DockerToActivationLogStoreTests.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
  tests/src/test/scala/whisk/core/controller/actions/test/SequenceAccountingTests.scala
  tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
  tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
  tests/src/test/scala/whisk/core/database/test/RemoveLogsTests.scala
  tests/src/test/scala/whisk/core/entity/test/DatastoreTests.scala
  tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala
  tests/src/test/scala/whisk/core/entity/test/ViewTests.scala
  tests/src/test/scala/whisk/core/entity/test/WhiskEntityTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/LoadBalancerDataTests.scala
Labels: performance, pgapproved, review

#3371 Make AuthKey parsing leaner.
  common/scala/src/main/scala/whisk/core/entity/AuthKey.scala
  common/scala/src/main/scala/whisk/core/entity/Secret.scala
  common/scala/src/main/scala/whisk/core/entity/UUID.scala
  tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala
Labels: performance, pgapproved, review

#3366 Adds method deleteAttachments to ArtifactStore
  common/scala/src/main/scala/whisk/core/database/ArtifactStore.scala
  common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
  common/scala/src/main/scala/whisk/core/database/DocumentFactory.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
  tests/build.gradle
  tests/src/test/scala/whisk/core/entity/test/DatastoreTests.scala
Labels: artifactstore, review

#3391 Add namespace-blacklist to invoker.
  ansible/files/namespace_throttlings_design_document_for_subjects_db.json
  ansible/roles/invoker/tasks/deploy.yml
  ansible/tasks/initdb.yml
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  core/invoker/src/main/scala/whisk/core/invoker/NamespaceBlacklist.scala
  tests/src/test/scala/whisk/core/invoker/test/NamespaceBlacklistTests.scala
Labels: review

#3409 Remove namespace configuration; use invoker's instead
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala
Labels: invoker, kubernetes, pgapproved

#3369 Use pureconfig for CouchDbRestStore
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/database/ArtifactStoreProvider.scala
  common/scala/src/main/scala/whisk/core/database/CouchDbStoreProvider.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskStore.scala
  core/controller/src/main/scala/whisk/core/controller/Authenticate.scala
  core/controller/src/main/scala/whisk/core/controller/Controller.scala
  core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
  core/controller/src/main/scala/whisk/core/entitlement/Collection.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  tests/src/test/resources/application.conf.j2
  tests/src/test/scala/common/WhiskProperties.java
  tests/src/test/scala/ha/ShootComponentsTests.scala
  tests/src/test/scala/whisk/core/cli/test/SequenceMigrationTests.scala
  tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
  tests/src/test/scala/whisk/core/database/test/CouchDbRestClientTests.scala
  tests/src/test/scala/whisk/core/database/test/DatabaseScriptTestUtils.scala
  tests/src/test/scala/whisk/core/entity/test/DatastoreTests.scala
  tests/src/test/scala/whisk/core/entity/test/ViewTests.scala
  tests/src/test/scala/whisk/core/invoker/test/NamespaceBlacklistTests.scala
Labels: reviewed

#3400 Use ShardingContainerPoolBalancer as the default.
  common/scala/src/main/resources/reference.conf
Labels: loadbalancer, performance, review

#3382 Cleanup script for unused entities in the whisks database.
  tests/src/test/scala/whisk/core/database/test/CleanUpWhisksDbSkriptTests.scala
  tools/db/cleanUpWhisks.py
Labels: review

#3417 Allow tabs for indentation in go code
  tools/build/scanCode.cfg
Labels: review

#3411 refactor KubernetesClient to separate invokerAgent; add forwarding LogStoreProvider
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClientWithInvokerAgent.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainer.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesInvokerAgentLogStore.scala
  tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
  tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala
Labels: invoker, kubernetes, logging, pgapproved, reviewed

#3424 Send active-ack in any case of a parseable message.
  common/scala/src/main/scala/whisk/http/ErrorResponse.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  core/invoker/src/main/scala/whisk/core/invoker/NamespaceBlacklist.scala
Labels: invoker, review

#3420 Add swift:4.1 with Codable to default set of runtimes
  actionRuntimes/swift4.1Action/Dockerfile
  actionRuntimes/swift4.1Action/build.gradle
  ansible/files/runtimes.json
  docs/actions.md
  docs/reference.md
  tests/src/test/scala/system/basic/WskBasicSwift3Tests.scala
  tests/src/test/scala/system/basic/WskRestBasicSwift41Tests.scala
  tests/src/test/scala/system/basic/WskRestUnicodeSwift41Tests.scala
  tools/build/compile_swift.sh
Labels: pgapproved, runtime, swift

#3440 Fixes Kubernetes logging issues from #3439 re: activation logs where timestamp errors caused logging failures
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainer.scala
Labels: invoker, kubernetes, logging, pgapproved

#3445 Fix outdated `limit section` in ansible doc
  ansible/README.md
Labels: documentation, ready, reviewed

#3449 Code clean up
  ansible/roles/controller/tasks/deploy.yml
  tests/src/test/scala/common/rest/WskRest.scala
  tests/src/test/scala/system/basic/WskRuleTests.scala
  tests/src/test/scala/whisk/core/connector/test/MessageFeedTests.scala
  tests/src/test/scala/whisk/core/controller/test/ControllerApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/WhiskAuthHelpers.scala
Labels: review

#2833 MesosContainerFactory
  common/scala/build.gradle
  common/scala/src/main/resources/application.conf
  common/scala/src/main/resources/reference.conf
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/mesos/MesosContainerFactory.scala
  common/scala/src/main/scala/whisk/core/mesos/MesosTask.scala
  docs/mesos.md
  tests/src/test/scala/whisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
Labels: invoker, pgapproved, review, spi

#3451 Fix several loadbalancer bugs.
  common/scala/src/main/scala/whisk/common/Logging.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: loadbalancer, performance, review

#3474 Ensure clean up testspace under wskadmin test.
  tests/src/test/scala/whisk/core/admin/WskAdminTests.scala
Labels: heisenbug, testing

#3435 CLI docs update and markdown linting.
  ansible/README.md
Labels: documentation

#3478 Remove deadcode and clone/own.
  tests/src/test/scala/common/rest/WskRest.scala
Labels: review

#3479 Makes wskadmin python2 and python3 compatible
  tools/admin/wskadmin
  tools/admin/wskutil.py
Labels: review, tooling

#3457 Ansible 2.4 deprecates ‘include’ in favor of ‘import_*’ and ‘include_tasks’
  ansible/initdb.yml
  ansible/logs.yml
  ansible/openwhisk.yml
  ansible/postdeploy.yml
  ansible/properties.yml
  ansible/provision_env_dist.yml
  ansible/recreateDesignDocs.yml
  ansible/registry.yml
  ansible/roles/apigateway/tasks/main.yml
  ansible/roles/cli-install/tasks/main.yml
  ansible/roles/cli/tasks/main.yml
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/controller/tasks/main.yml
  ansible/roles/couchdb/tasks/main.yml
  ansible/roles/docker/tasks/main.yml
  ansible/roles/invoker/tasks/deploy.yml
  ansible/roles/invoker/tasks/main.yml
  ansible/roles/kafka/tasks/main.yml
  ansible/roles/nginx/tasks/main.yml
  ansible/roles/prereq/tasks/main.yml
  ansible/roles/redis/tasks/main.yml
  ansible/roles/registry/tasks/main.yml
  ansible/roles/routemgmt/tasks/main.yml
  ansible/roles/whiskhost/tasks/deploy.yml
  ansible/roles/whiskhost/tasks/main.yml
  ansible/roles/zookeeper/tasks/main.yml
  ansible/routemgmt.yml
  ansible/tasks/initdb.yml
  ansible/tasks/recreateViews.yml
  ansible/tasks/wipeDatabase.yml
  ansible/wipe.yml
Labels: ansible, review

#3473 Support string based status code from actions.
  core/controller/src/main/scala/whisk/core/controller/WebActions.scala
  tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Labels: awaits-feedback, controller, ready

#3442 Add -o option to overwrite target files
  ansible/roles/cli/tasks/deploy.yml
  ansible/roles/kafka/tasks/deploy.yml
Labels: ansible, review

#3485 Action time limit test cleanup
  tests/dat/actions/Sleep.java
  tests/dat/actions/TimedOut.java
  tests/dat/actions/sleep.jar
  tests/dat/actions/sleep.js
  tests/dat/actions/sleep.py
  tests/dat/actions/timedout.jar
  tests/dat/actions/timedout.py
  tests/dat/actions/timeout.js
  tests/src/test/scala/limits/ThrottleTests.scala
  tests/src/test/scala/system/basic/WskBasicTests.scala
  tests/src/test/scala/system/basic/WskSequenceTests.scala
  tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
  tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala
  tests/src/test/scala/whisk/core/limits/MaxActionDurationTests.scala
Labels: review
