Repository apache/openwhisk, pull requests merged in 2018-05, with the labels that each got.

#3598 Update all .md and .sh files to pass scancode for compliance.
  CONTRIBUTING.md
  README.md
  actionRuntimes/actionProxy/README.md
  common/scala/copyJMXFiles.sh
  common/scala/transformEnvironment.sh
  docs/feeds.md
  docs/images/README.md
  docs/mobile_sdk.md
  docs/parameters.md
  docs/rest_api.md
  docs/webactions.md
  gradle/README.md
  tests/dat/blackbox/badaction/README.md
  tests/dat/blackbox/badproxy/README.md
  tools/admin/README.md
  tools/build/compile_swift.sh
  tools/db/README.md
  tools/dev/README.md
  tools/git/README.md
  tools/git/pre-commit-scalafmt-gradlew.sh
  tools/git/pre-commit-scalafmt-native.sh
  tools/macos/README.md
  tools/macos/docker-machine/README.md
  tools/ubuntu-setup/README.md
Labels: apache

#3602 Update build to use latest scancode .cfg for .md and .sh
  tools/travis/build.sh
Labels: apache, build

#3601 Change the LICENSE file into the correct format defined in openwhisk release
  LICENSE.txt
Labels: wip

#3199 One tid for the whole system.
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  ansible/roles/nginx/templates/nginx.conf.j2
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/common/TransactionId.scala
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/http/BasicHttpService.scala
  common/scala/src/main/scala/whisk/http/ErrorResponse.scala
  core/controller/src/main/scala/whisk/core/controller/Controller.scala
  core/controller/src/main/scala/whisk/core/controller/Triggers.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerServer.scala
  tests/src/test/scala/whisk/common/SchedulerTests.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
  tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
  tests/src/test/scala/whisk/core/controller/test/PackagesApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
  tests/src/test/scala/whisk/core/database/test/DbUtils.scala
  tests/src/test/scala/whisk/core/database/test/DocumentHandlerTests.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreBehaviorBase.scala
  tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala
Labels: review

#3592 Make limit overcommit relative to the actual cluster size.
  core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
Labels: controller, review

#3604 Limit cipher suites used for Kafka SSL
  ansible/group_vars/all
  ansible/roles/kafka/tasks/deploy.yml
Labels: deployment, kafka

#3609 Support "+json" content-types as WebAction input.
  common/scala/src/main/scala/whisk/http/LenientSprayJsonSupport.scala
  core/controller/src/main/scala/whisk/core/controller/WebActions.scala
  tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Labels: API, review

#3626 Add ASF license headers to all Scala .conf files.
  .scalafmt.conf
  common/scala/src/main/resources/application.conf
  common/scala/src/main/resources/logging.conf
  common/scala/src/main/resources/reference.conf
  core/controller/src/main/resources/application.conf
  core/controller/src/main/resources/reference.conf
  core/invoker/src/main/resources/application.conf
Labels: apache, review

#2855 Cache database attachments
  common/scala/src/main/scala/whisk/core/database/DocumentFactory.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
  tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/whisk/core/database/test/DbUtils.scala
Labels: controller, review

#3642 Fix README.md's scanCode issues.
  README.md
Labels: review

#3644 Allow more special characters in EntityName.
  common/scala/src/main/scala/whisk/core/entity/EntityPath.scala
  tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala
Labels: review

#3613 Split test jobs in Travis
  .travis.yml
  ansible/logs.yml
  common/scala/src/main/scala/whisk/core/database/memory/MemoryArtifactStore.scala
  tests/README.md
  tests/build.gradle
  tools/build/checkLogs.py
  tools/build/redo
  tools/travis/README.md
  tools/travis/checkAndUploadLogs.sh
  tools/travis/distDocker.sh
  tools/travis/runSystemTests.sh
  tools/travis/runTests.sh
  tools/travis/runUnitTests.sh
  tools/travis/scan.sh
  tools/travis/setupPrereq.sh
  tools/travis/setupSystem.sh
Labels: build, testing

#3659 Assure all Dockerfiles have ASF header.
  actionRuntimes/actionProxy/Dockerfile
  actionRuntimes/javaAction/Dockerfile
  actionRuntimes/nodejs6Action/Dockerfile
  actionRuntimes/nodejs8Action/Dockerfile
  actionRuntimes/php7.1Action/Dockerfile
  actionRuntimes/python2Action/Dockerfile
  actionRuntimes/pythonAction/Dockerfile
  actionRuntimes/swift3.1.1Action/Dockerfile
  actionRuntimes/swift4.1Action/Dockerfile
  common/scala/Dockerfile
  core/controller/Dockerfile
  core/invoker/Dockerfile
  sdk/docker/Dockerfile
Labels: apache, review

#3658 Assure nginx verifies upstream ssl certs
  ansible/roles/nginx/templates/nginx.conf.j2
Labels: deployment, nginx

#3652 Disable Slf4jLogger startup log in test runs
  tests/src/test/resources/logback-test.xml
Labels: testing

#3670 Add ASF Headers to .groovy source files.
  tools/dev/src/main/groovy/couchdbViews.groovy
  tools/jenkins/apache/dockerhub.groovy
Labels: apache, license

#3684 Update last, edge-case files without ASF headers.
  actionRuntimes/actionProxy/build.gradle
  actionRuntimes/javaAction/build.gradle
  actionRuntimes/nodejs6Action/build.gradle
  actionRuntimes/nodejs8Action/build.gradle
  actionRuntimes/php7.1Action/build.gradle
  actionRuntimes/python2Action/build.gradle
  actionRuntimes/pythonAction/build.gradle
  actionRuntimes/swift3.1.1Action/build.gradle
  actionRuntimes/swift4.1Action/build.gradle
  ansible/environments/distributed/group_vars/all
  ansible/environments/docker-machine/group_vars/all
  ansible/environments/local/group_vars/all
  ansible/environments/vagrant/group_vars/all
  ansible/group_vars/all
  build.gradle
  common/scala/build.gradle
  common/scala/src/main/resources/logback.xml
  core/controller/build.gradle
  core/invoker/build.gradle
  gradle/docker.gradle
  gradle/wrapper/gradle-wrapper.properties
  performance/gatling_tests/build.gradle
  sdk/docker/build.gradle
  settings.gradle
  tests/build.gradle
  tests/dat/blackbox/badaction/build.gradle
  tests/dat/blackbox/badproxy/build.gradle
  tools/dev/build.gradle
  tools/eclipse/scala.properties
  tools/vagrant/Vagrantfile
Labels: apache, compliance, review

#3672 Add retries in test around package list and enhance debugging inform…
  tests/src/test/scala/whisk/core/cli/test/WskEntitlementTests.scala
Labels: review

#3695 Use method links and correct method name.
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
Labels: review

#3702 Add ASF license to optional XML files and last gradle file.
  common/scala/src/main/resources/logback.xml
  tests/dat/actions/unicode/build.gradle
  tests/performance/gatling_tests/src/gatling/resources/conf/logback.xml
  tests/src/test/resources/logback-test.xml
Labels: compliance, review

#3502 Immutable attachments via putAndAttach
  common/scala/src/main/scala/whisk/core/database/ArtifactStore.scala
  common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
  common/scala/src/main/scala/whisk/core/database/DocumentFactory.scala
  common/scala/src/main/scala/whisk/core/database/MultipleReadersSingleWriterCache.scala
  common/scala/src/main/scala/whisk/core/database/memory/MemoryArtifactStore.scala
  common/scala/src/main/scala/whisk/core/entity/Attachments.scala
  common/scala/src/main/scala/whisk/core/entity/Exec.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala
  core/controller/src/main/scala/whisk/core/controller/ApiUtils.scala
  core/controller/src/main/scala/whisk/core/controller/Rules.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
  tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/whisk/core/database/test/AttachmentTests.scala
  tests/src/test/scala/whisk/core/database/test/DbUtils.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreAttachmentBehaviors.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreBehavior.scala
  tests/src/test/scala/whisk/core/entity/test/DatastoreTests.scala
Labels: artifactstore

#3708 Single build.gradle file missing ASF license header
  tests/dat/actions/unicode/build.gradle
Labels: apache, compliance, review

#3699 Add gatling-throughput test for cold invocations.
  .travis.yml
  tests/performance/README.md
  tests/performance/gatling_tests/src/gatling/resources/data/users.csv
  tests/performance/gatling_tests/src/gatling/scala/ColdBlockingInvokeSimulation.scala
Labels: review

#3669 Make stemcells configurable by deployment
  ansible/files/runtimes.json
  common/scala/src/main/scala/whisk/core/entity/ExecManifest.scala
  common/scala/src/main/scala/whisk/core/entity/Size.scala
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
  tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala
  tests/src/test/scala/whisk/core/entity/test/ExecManifestTests.scala
Labels: controller, deployment, invoker, review
