Repository apache/openwhisk, pull requests merged in 2018-07, with the labels that each got.

#3818 Make HttpUtils actually use only one connection and harden connection release.
  common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala
Labels: bug, priority:high, review

#3832 Bump wskadmin's request timeout.
  tools/admin/wskutil.py
Labels: heisenbug, review

#3778 Add documentation to the loadbalancer.
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
Labels: documentation, loadbalancer

#3831 Add metrics to monitor the memory, that usercontainers are consuming …
  common/scala/src/main/scala/whisk/common/Logging.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: review

#3830 Include rotating user log filename in system logs
  common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
Labels: review

#3836 Use a PoolingConnectionManager even for single connection use-cases.
  common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala
Labels: review

#3736 Add support for PHP 7.2 runtime
  ansible/files/runtimes.json
  core/controller/src/main/resources/apiv1swagger.json
  docs/actions-php.md
  docs/webactions.md
Labels: runtime

#3794 Allow Elasticsearch client to retrieve hit count
  common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchRestClient.scala
  tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchRestClientTests.scala
Labels: review

#3842 Revert hardening of HttpUtils.
  common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala
Labels: review

#3795 Allow Elasticsearch 'must' query to take an array of 'ranges'
  common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchRestClient.scala
  tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchRestClientTests.scala
Labels: companion, review

#3844 Add test for empty initializer. Document other tests.
  tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala
  tools/build/redo
Labels: review, testing

#3843 Properly consume and optimize reading of http entities, drop connection reuse.
  common/scala/build.gradle
  common/scala/src/main/scala/whisk/core/containerpool/HttpUtils.scala
Labels: invoker, review

#3785 Refactor invoker roles
  ansible/invoker.yml
  ansible/roles/invoker/tasks/clean.yml
  ansible/roles/invoker/tasks/deploy.yml
Labels: companion, review

#3790 Generic plugins for deployment
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/controller/tasks/join_akka_cluster.yml
Labels: companion, review

#3837 Document adding a new runtime kind.
  docs/actions-new.md
  docs/actions-swift.md
  docs/actions.md
Labels: documentation, review

#3840 Remove runtime tests, simplify Rest vs CLI test hierarchy, add sniff test for all runtimes
  docs/actions-new.md
  tests/dat/actions/unicode.tests/java.bin
  tests/dat/actions/unicode.tests/nodejs:6.txt
  tests/dat/actions/unicode.tests/nodejs:8.txt
  tests/dat/actions/unicode.tests/php:7.1.txt
  tests/dat/actions/unicode.tests/php:7.2.txt
  tests/dat/actions/unicode.tests/python.txt
  tests/dat/actions/unicode.tests/python:2.txt
  tests/dat/actions/unicode.tests/python:3.txt
  tests/dat/actions/unicode.tests/src/java/unicode/build.gradle
  tests/dat/actions/unicode.tests/src/java/unicode/src/main/java/Unicode.java
  tests/dat/actions/unicode.tests/swift:3.1.1.txt
  tests/dat/actions/unicode.tests/swift:4.1.txt
  tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala
  tests/src/test/scala/common/rest/WskRestOperations.scala
  tests/src/test/scala/system/basic/WskActionTests.scala
  tests/src/test/scala/system/basic/WskActivationTests.scala
  tests/src/test/scala/system/basic/WskBasicJavaTests.scala
  tests/src/test/scala/system/basic/WskBasicNode6Tests.scala
  tests/src/test/scala/system/basic/WskBasicNode8Tests.scala
  tests/src/test/scala/system/basic/WskBasicNodeDefaultTests.scala
  tests/src/test/scala/system/basic/WskBasicPythonTests.scala
  tests/src/test/scala/system/basic/WskBasicSwift3Tests.scala
  tests/src/test/scala/system/basic/WskConductorTests.scala
  tests/src/test/scala/system/basic/WskPackageTests.scala
  tests/src/test/scala/system/basic/WskRestActionTests.scala
  tests/src/test/scala/system/basic/WskRestActivationTests.scala
  tests/src/test/scala/system/basic/WskRestBasicJavaTests.scala
  tests/src/test/scala/system/basic/WskRestBasicNode6Tests.scala
  tests/src/test/scala/system/basic/WskRestBasicNode8Tests.scala
  tests/src/test/scala/system/basic/WskRestBasicNodeDefaultTests.scala
  tests/src/test/scala/system/basic/WskRestBasicPythonTests.scala
  tests/src/test/scala/system/basic/WskRestBasicSwift311Tests.scala
  tests/src/test/scala/system/basic/WskRestBasicSwift41Tests.scala
  tests/src/test/scala/system/basic/WskRestBasicTests.scala
  tests/src/test/scala/system/basic/WskRestConductorTests.scala
  tests/src/test/scala/system/basic/WskRestPackageTests.scala
  tests/src/test/scala/system/basic/WskRestSequenceTests.scala
  tests/src/test/scala/system/basic/WskRestUnicodeJavaTests.scala
  tests/src/test/scala/system/basic/WskRestUnicodeNode6Tests.scala
  tests/src/test/scala/system/basic/WskRestUnicodeNode8Tests.scala
  tests/src/test/scala/system/basic/WskRestUnicodePython2Tests.scala
  tests/src/test/scala/system/basic/WskRestUnicodePython3Tests.scala
  tests/src/test/scala/system/basic/WskRestUnicodeSwift311Tests.scala
  tests/src/test/scala/system/basic/WskRestUnicodeSwift41Tests.scala
  tests/src/test/scala/system/basic/WskSequenceTests.scala
  tests/src/test/scala/system/basic/WskUnicodeTests.scala
  tests/src/test/scala/whisk/core/cli/test/WskRestBasicUsageTests.scala
  tests/src/test/scala/whisk/core/cli/test/WskRestWebActionsTests.scala
  tests/src/test/scala/whisk/core/cli/test/WskWebActionsTests.scala
  tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/SequenceApiTests.scala
Labels: review, testing

#3859 Add action limits to API host standard response
  common/scala/src/main/scala/whisk/core/entity/LogLimit.scala
  common/scala/src/main/scala/whisk/core/entity/MemoryLimit.scala
  common/scala/src/main/scala/whisk/core/entity/TimeLimit.scala
  core/controller/src/main/scala/whisk/core/controller/Controller.scala
  tests/src/test/scala/actionContainers/BasicActionRunnerTests.scala
  tests/src/test/scala/system/basic/WskActionTests.scala
  tests/src/test/scala/system/basic/WskSequenceTests.scala
  tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/ControllerApiTests.scala
Labels: controller, enhancement, review, testing

#3848 Adjust citool to work with Travis build matrix.
  tools/build/README.md
  tools/build/citool
Labels: review, tooling

#3870 Cleanup akka-http client usages.
  common/scala/src/main/scala/whisk/core/database/CloudantRestClient.scala
  common/scala/src/main/scala/whisk/core/database/CouchDbRestClient.scala
  common/scala/src/main/scala/whisk/http/PoolingRestClient.scala
Labels: review

#3849 Allow Elasticsearch client to skip query result hits
  common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchRestClient.scala
  tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchLogStoreTests.scala
  tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchRestClientTests.scala
Labels: companion, review

#3822 Introduce entitlement spi
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  common/scala/src/main/resources/reference.conf
  core/controller/src/main/scala/whisk/core/controller/Controller.scala
  core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
  core/controller/src/main/scala/whisk/core/entitlement/LocalEntitlement.scala
Labels: review

#3867 Refactor database-related variables to avoid duplication in every environment.
  ansible/couchdb.yml
  ansible/environments/docker-machine/group_vars/all
  ansible/environments/local/group_vars/all
  ansible/environments/local/hosts.j2.ini
  ansible/environments/vagrant/group_vars/all
  ansible/environments/vagrant/hosts
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/couchdb/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  ansible/tasks/db/checkDb.yml
  ansible/tasks/db/recreateDb.yml
  ansible/tasks/db/recreateDoc.yml
  ansible/templates/whisk.conf.j2
  ansible/templates/whisk.properties.j2
  tests/src/test/resources/application.conf.j2
Labels: couchdb, deployment, review

#3874 Fix warnings in python scripts.
  tools/build/citool
  tools/build/redo
  tools/travis/flake8.sh
Labels: review

#3866 Fix invokerId assignment path in zookeeper
  core/invoker/build.gradle
  core/invoker/src/main/scala/whisk/core/invoker/InstanceIdAssigner.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  settings.gradle
  tests/build.gradle
  tests/src/test/scala/whisk/core/invoker/test/InstanceIdAssignerTests.scala
Labels: companion, invoker

#3829 Introduce SPI to swap authentication directives
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  common/scala/src/main/resources/reference.conf
  core/controller/src/main/scala/whisk/core/controller/AuthenticatedRoute.scala
  core/controller/src/main/scala/whisk/core/controller/BasicAuthenticationDirective.scala
  core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
  tests/src/test/scala/whisk/core/controller/test/BasicAuthenticateTests.scala
Labels: review, spi

#3881 Limit TLS protocols used for kafka and controller
  ansible/group_vars/all
  ansible/roles/kafka/tasks/deploy.yml
  core/controller/src/main/resources/application.conf
Labels: controller, kafka, security

#3876 Use separate db users for deployed components.
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  ansible/tasks/db/checkDb.yml
  ansible/tasks/db/createUsers.yml
  ansible/tasks/db/grantPermissions.yml
  ansible/tasks/initdb.yml
  ansible/tasks/recreateViews.yml
  ansible/tasks/wipeDatabase.yml
  ansible/templates/db_local.ini.j2
Labels: review

#3887 Implement full specification of docker image names.
  common/scala/build.gradle
  common/scala/src/main/scala/whisk/core/entity/ExecManifest.scala
  tests/src/test/scala/whisk/core/entity/test/ExecManifestTests.scala
Labels: bug, review

#3893 Always create users-database in couchdb, independently from the amoun…
  ansible/roles/couchdb/tasks/deploy.yml
  ansible/tasks/db/grantPermissions.yml
Labels: review

#3895 Unify Entitlement SPI signatures
  core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
  core/controller/src/main/scala/whisk/core/entitlement/LocalEntitlement.scala
  tests/src/test/scala/whisk/core/controller/test/EntitlementProviderTests.scala
  tests/src/test/scala/whisk/core/controller/test/PackageActionsApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Labels: review

#3889 make request id header name comparison case insensitive
  common/scala/src/main/scala/whisk/common/TransactionId.scala
  common/scala/src/main/scala/whisk/http/BasicHttpService.scala
Labels: review

#3813 Recover image pulls by trying to run the container anyways.
  core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
  core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
  docs/actions-docker.md
  tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
Labels: docker, invoker, review

#3853 Set erlang magic cookie for couchdb
  ansible/roles/couchdb/tasks/deploy.yml
  ansible/tasks/gen_erl_cookie.yml
Labels: couchdb, review

#3873 Cleanup SPIs, move ActivationStore to whisk.core.database.
  common/scala/src/main/resources/reference.conf
  common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationLogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchLogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/LogDriverLogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/LogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/SplunkLogStore.scala
  common/scala/src/main/scala/whisk/core/database/ActivationStore.scala
  common/scala/src/main/scala/whisk/core/database/ArtifactActivationStore.scala
  common/scala/src/main/scala/whisk/core/mesos/MesosContainerFactory.scala
  core/controller/src/main/scala/whisk/core/controller/Actions.scala
  core/controller/src/main/scala/whisk/core/controller/Activations.scala
  core/controller/src/main/scala/whisk/core/controller/Controller.scala
  core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
  core/controller/src/main/scala/whisk/core/controller/Triggers.scala
  core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
  core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancer.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesInvokerAgentLogStore.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  tests/src/test/scala/whisk/core/containerpool/logging/test/DockerToActivationLogStoreTests.scala
  tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
Labels: review

#3892 Use the authz provider to retrieve the identity of the namespace
  core/controller/src/main/scala/whisk/core/controller/BasicAuthenticationDirective.scala
  core/controller/src/main/scala/whisk/core/controller/RestAPIs.scala
  core/controller/src/main/scala/whisk/core/controller/WebActions.scala
Labels: reviewed

#3767 introduce timeout factor to control invoker queue behavior
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  core/controller/src/main/resources/reference.conf
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: review

#3884 Document metrics generated within OpenWhisk
  docs/metrics.md
Labels: documentation, review

#3898 Add pause in latency test to handle asynchrounous log collecting.
  .travis.yml
  tests/performance/README.md
  tests/performance/gatling_tests/src/gatling/scala/LatencySimulation.scala
Labels: review

#3875 Throttle the system based on active-ack timeouts.
  ansible/README.md
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  ansible/templates/whisk.properties.j2
  common/scala/src/main/scala/whisk/common/Logging.scala
  common/scala/src/main/scala/whisk/common/RingBuffer.scala
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  core/controller/src/main/scala/whisk/core/controller/Actions.scala
  core/controller/src/main/scala/whisk/core/controller/Controller.scala
  core/controller/src/main/scala/whisk/core/controller/WebActions.scala
  core/controller/src/main/scala/whisk/core/entitlement/ActivationThrottler.scala
  core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  tests/performance/preparation/deploy.sh
  tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: review

#2941 Add api gateway test that uses custom package for action
  tests/src/test/scala/whisk/core/cli/test/ApiGwRestBasicTests.scala
Labels: apigw, ready, review, testing

#3897 Do not abort conductor action execution when component action is invalid, not found, not accessible or when composition is too long
  core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
  docs/conductors.md
  tests/src/test/scala/system/basic/WskConductorTests.scala
  tests/src/test/scala/whisk/core/controller/test/ConductorsApiTests.scala
Labels: review

#3912 Fix max.poll.interval.ms setting of KafkaConsumer.
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
  common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
  common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
  tests/src/test/scala/services/KafkaConnectorTests.scala
Labels: kafka, review

#3915 Fix misspelled or wrongly named types.
  common/scala/src/main/scala/whisk/common/ForcibleSemaphore.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  tests/src/test/scala/whisk/common/ForcibleSemaphoreTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/InvokerSupervisionTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: companion, review

#3914 Delete unused files in whisk.common.
  common/scala/src/main/scala/whisk/common/DateUtil.scala
  common/scala/src/main/scala/whisk/common/TimingUtil.scala
Labels: review

#3725 Add Ruby2.5 runtime support
  ansible/files/runtimes.json
  core/controller/src/main/resources/apiv1swagger.json
  docs/actions-ruby.md
  docs/actions.md
  docs/parameters.md
  tests/dat/actions/unicode.tests/ruby-2.5.txt
Labels: review, runtime

#3799 Display proper error when sequence invocation fails due to missing component
  core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
  tests/src/test/scala/whisk/core/controller/test/SequenceApiTests.scala
Labels: awaits-reviewer, bug, review

#3903 Manually create user log files
  common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
Labels: awaits-reviewer, review

#3894 Refactor invoker command line parsing.
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
Labels: companion, review

#3922 Improve robustness of KafkaConsumerConnector
  common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
Labels: kafka
