Repository apache/openwhisk, pull requests merged in 2018-08, with the labels that each got.

#3913 Bump kafka-clients version to 2.0.0.
  common/scala/build.gradle
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
  common/scala/src/main/scala/whisk/utils/TimeHelpers.scala
Labels: kafka, review

#3910 Allow non-json skip_pull_runtimes to be passed as True.
  ansible/roles/invoker/tasks/deploy.yml
  docs/actions-ruby.md
  tests/src/test/resources/application.conf.j2
  tools/travis/README.md
Labels: ansible, review

#3935 Tune down excessive Zookeeper logging in core components and tests.
  tests/src/test/resources/logback-test.xml
Labels: logging, review

#3933 Run 'limits' tests in travis.
  tests/build.gradle
Labels: review, testing

#3934 Adjust Kafka's config to not contain any more warnings.
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
  common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
Labels: kafka, review

#3878 Validate the Controller Swagger spec matches the impl
  core/controller/src/main/resources/apiv1swagger.json
  tests/build.gradle
  tests/src/test/resources/swagger-config.json
  tests/src/test/scala/common/rest/SwaggerValidator.scala
  tests/src/test/scala/common/rest/WskRestOperations.scala
  tools/travis/runTests.sh
Labels: review

#3942 make error count and percentage configurable for gatling tests
  tests/performance/README.md
  tests/performance/gatling_tests/src/gatling/scala/ApiV1Simulation.scala
  tests/performance/gatling_tests/src/gatling/scala/BlockingInvokeOneActionSimulation.scala
  tests/performance/gatling_tests/src/gatling/scala/ColdBlockingInvokeSimulation.scala
  tests/performance/gatling_tests/src/gatling/scala/LatencySimulation.scala
Labels: review

#3698 Make amount of parallel docker runs configurable.
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerClient.scala
Labels: invoker, review

#3960 Make gradle and dependency downloads more stable.
  .travis.yml
  tools/travis/setup.sh
Labels: build, review

#3972 Log possible errors around creation of kafka clients.
  common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
  common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
  common/scala/src/main/scala/whisk/utils/Exceptions.scala
Labels: review

#3963 k8s: implement invoker-node affinity and eliminate usage of kubectl
  common/scala/build.gradle
  core/invoker/Dockerfile
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala
  tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
Labels: invoker, kubernetes

#3890 Use ArtifactStore to manipulate data in NamespaceBlacklistTests
  tests/src/test/scala/whisk/core/database/test/DbUtils.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreSubjectQueryBehaviors.scala
  tests/src/test/scala/whisk/core/invoker/test/NamespaceBlacklistTests.scala
Labels: artifactstore, review

#3971 Bump fetch.max.wait of Kafka-consumers to lower the load on Kafka in large systems.
  common/scala/src/main/resources/application.conf
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
Labels: review

#3798 Allow for activation store to accept user and request information
  common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationLogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchLogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/LogDriverLogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/LogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/SplunkLogStore.scala
  common/scala/src/main/scala/whisk/core/database/ActivationStore.scala
  common/scala/src/main/scala/whisk/core/database/ArtifactActivationStore.scala
  core/controller/src/main/scala/whisk/core/controller/Activations.scala
  core/controller/src/main/scala/whisk/core/controller/Triggers.scala
  core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
  core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchLogStoreTests.scala
  tests/src/test/scala/whisk/core/containerpool/logging/SplunkLogStoreTests.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
  tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/ControllerTestCommon.scala
  tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala
Labels: awaits-reviewer, review

#3945 Treat action code as attachments
  ansible/files/runtimes.json
  common/scala/src/main/scala/whisk/core/entity/Exec.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
  tests/performance/gatling_tests/src/gatling/scala/ColdBlockingInvokeSimulation.scala
  tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/whisk/core/database/test/AttachmentCompatibilityTests.scala
  tests/src/test/scala/whisk/core/database/test/CacheConcurrencyTests.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreAttachmentBehaviors.scala
  tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala
  tests/src/test/scala/whisk/core/entity/test/ExecTests.scala
  tools/db/moveCodeToAttachment.py
Labels: companion, review

#3747 Memory based loadbalancing
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  ansible/templates/whisk.properties.j2
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/containerpool/Container.scala
  common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala
  common/scala/src/main/scala/whisk/core/entity/Size.scala
  core/controller/src/main/resources/reference.conf
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  tests/src/test/scala/whisk/core/containerpool/logging/test/DockerToActivationFileLogStoreTests.scala
  tests/src/test/scala/whisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
  tests/src/test/scala/whisk/core/entity/test/SizeTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: companion, loadbalancer

#3985 Make ansible script to grant permissions more general.
  ansible/tasks/db/createUsers.yml
  ansible/tasks/db/grantPermissions.yml
Labels: review

#3984 Simplify configuring OpenWhisk
  common/scala/transformEnvironment.sh
Labels: deployment, review

#3909 Refactor sentinel message into shared place.
  common/scala/src/main/scala/whisk/core/containerpool/Container.scala
  core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainer.scala
  tests/src/test/scala/actionContainers/ActionContainer.scala
  tests/src/test/scala/system/basic/WskRestBasicTests.scala
  tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
  tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
  tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala
Labels: ready

#3970 Fix macOS bash update instructions in docs/cli.md
  docs/cli.md
Labels: documentation, review

#3993 Correct default-value for user-memory in Loadbalancer.
  core/controller/src/main/resources/reference.conf
Labels: review

#3955 Add an variable to set the timezone for all of components
  ansible/README.md
  ansible/group_vars/all
  ansible/roles/apigateway/tasks/deploy.yml
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/couchdb/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  ansible/roles/kafka/tasks/deploy.yml
  ansible/roles/nginx/tasks/deploy.yml
  ansible/roles/redis/tasks/deploy.yml
  ansible/roles/zookeeper/tasks/deploy.yml
Labels: deployment, review
