Repository apache/openwhisk, pull requests merged in 2018-02, with the labels that each got.

#3269 change tmp dir for vagrant
  ansible/environments/local/group_vars/all
  tools/vagrant/Vagrantfile
Labels: ready

#3270 Remove unneeded logline and revive old marker.
  core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
Labels: controller, review

#3271 Rewrite Kafka test and accomodate for eventual consistency.
  tests/src/test/scala/services/KafkaConnectorTests.scala
Labels: bug, heisenbug, kafka, review

#3268 Cleanup replication doc after testing replay of database.
  tests/src/test/scala/whisk/core/database/test/ReplicatorTests.scala
Labels: review

#3256 Refactor some bits of the triggers API.
  core/controller/src/main/scala/whisk/core/controller/Triggers.scala
Labels: controller, review

#3273 Wait for logs based on intervals not based on total processing time.
  core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainer.scala
  tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
Labels: alert, heisenbug, invoker, review

#3259 use PureConfig for misc. runtimesManifest configuration
  ansible/environments/docker-machine/group_vars/all
  ansible/environments/local/group_vars/all
  ansible/files/runtimes.json
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/entity/ExecManifest.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  tests/src/test/scala/whisk/core/entity/test/ExecManifestTests.scala
Labels: companion, deployment, pgapproved, review

#3260 Enhance the RestResult with more information to debug failing tests e…
  tests/src/test/scala/common/rest/WskRest.scala
Labels: review

#3109 Add binary, image, and main properties to WhiskActionMetaData
  common/scala/src/main/scala/whisk/core/entity/Exec.scala
  tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
  tests/src/test/scala/whisk/core/entity/test/ExecHelpers.scala
Labels: controller, review

#3240 Add a loadbalancer with local state and horizontal invoker sharding.
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  common/scala/src/main/scala/whisk/common/ForcableSemaphore.scala
  core/controller/src/main/scala/whisk/core/controller/Controller.scala
  core/controller/src/main/scala/whisk/core/entitlement/ActivationThrottler.scala
  core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
  core/controller/src/main/scala/whisk/core/entitlement/RateThrottler.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/InvokerSupervision.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancer.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  docs/deploy.md
  tests/src/test/scala/limits/ThrottleTests.scala
  tests/src/test/scala/whisk/common/ForcableSemaphoreTests.scala
  tests/src/test/scala/whisk/core/controller/test/RateThrottleTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: loadbalancer, performance, review

#3280 Replace asString and asBool with generic method.
  common/scala/src/main/scala/whisk/core/entity/Parameter.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskAction.scala
  core/controller/src/main/scala/whisk/core/controller/WebActions.scala
Labels: review

#3288 Run container pool logging tests
  tests/src/test/scala/whisk/core/containerpool/logging/LogDriverLogStoreTests.scala
  tests/src/test/scala/whisk/core/containerpool/logging/SplunkLogStoreTests.scala
  tests/src/test/scala/whisk/core/containerpool/logging/test/DockerToActivationFileLogStoreTests.scala
  tests/src/test/scala/whisk/core/containerpool/logging/test/DockerToActivationLogStoreTests.scala
Labels: alert, review

#3254 Preserve rule status when rule is updated
  core/controller/src/main/scala/whisk/core/controller/Rules.scala
  tests/src/test/scala/system/basic/WskRuleTests.scala
  tests/src/test/scala/whisk/core/controller/test/RulesApiTests.scala
Labels: controller, review

#3244 Move parameter docs to separate page, add package params docs
  docs/actions.md
  docs/parameters.md
Labels: documentation, review

#3202 Support action continuations in the controller
  common/scala/src/main/scala/whisk/core/entity/Parameter.scala
  common/scala/src/main/scala/whisk/core/entity/WhiskActivation.scala
  common/scala/src/main/scala/whisk/http/ErrorResponse.scala
  core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
  docs/conductors.md
  tests/dat/actions/conductor.js
  tests/dat/actions/step.js
  tests/src/test/scala/system/basic/WskConductorTests.scala
  tests/src/test/scala/system/basic/WskRestConductorTests.scala
  tests/src/test/scala/whisk/core/controller/test/ConductorsApiTests.scala
Labels: controller, review

#3290 Check all testfiles to actually contain the `RunWith` annotation.
  tests/src/test/scala/whisk/core/cli/test/TestJsonArgs.scala
  tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/LoadBalancerDataTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/SeedNodesProviderTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/SharedDataServiceTests.scala
  tools/travis/build.sh
Labels: alert, review

#3266 Use always all available controllers.
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/nginx/templates/nginx.conf.j2
  ansible/templates/whisk.properties.j2
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
  tests/src/test/scala/limits/ThrottleTests.scala
Labels: review

#3296 Bump swift test-timeout to 2 minutes.
  tests/src/test/scala/common/WskTestHelpers.scala
  tests/src/test/scala/whisk/core/cli/test/Swift311Tests.scala
Labels: alert, review

#3284 Remove finely granulated metrics.
  common/scala/src/main/scala/whisk/common/Logging.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
Labels: review

#3300 For MacOSX using docker-for-mac, do not use runc.
  ansible/environments/local/group_vars/all
Labels: deployment, review

#2938 Convert inline code to attachment in database
  tools/db/README.md
  tools/db/moveCodeToAttachment.py
Labels: couchdb, review

#3301 Add HTTP request timeout.
  tools/admin/wskutil.py
Labels: review

#3303 Actually retry package remove on conflict.
  tests/src/test/scala/common/WskTestHelpers.scala
Labels: alert, review

#3258 Encrypt data in motion - Kafka
  .gitignore
  ansible/files/genssl.sh
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  ansible/roles/kafka/tasks/deploy.yml
  ansible/roles/nginx/files/genssl.sh
  ansible/setup.yml
  ansible/tasks/writeWhiskProperties.yml
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
  common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
  common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  tests/src/test/resources/application.conf.j2
  tests/src/test/scala/services/KafkaConnectorTests.scala
Labels: deployment, review

#3262 Handle trigger activations with inactive rules
  common/scala/src/main/scala/whisk/http/ErrorResponse.scala
  core/controller/src/main/resources/apiv1swagger.json
  core/controller/src/main/scala/whisk/core/controller/Triggers.scala
  tests/src/test/scala/system/basic/WskBasicTests.scala
  tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala
Labels: controller, review

#3308 Let the AssetCleaner return the result of the test.
  tests/src/test/scala/common/WskTestHelpers.scala
Labels: alert, review

#3305 Fix misspelled words
  docs/use_cases.md
Labels: documentation, review

#3311 Bump default retry timeout to 50 milliseconds.
  common/scala/src/main/scala/whisk/utils/Retry.scala
Labels: alert, pgapproved, review

#3298 Attempt to resolve action name from conductor to a fully qualified name for added convenience.
  common/scala/src/main/scala/whisk/core/entity/FullyQualifiedEntityName.scala
  common/scala/src/main/scala/whisk/http/ErrorResponse.scala
  core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
  docs/conductors.md
  tests/src/test/scala/system/basic/WskBasicNode6Tests.scala
  tests/src/test/scala/system/basic/WskConductorTests.scala
  tests/src/test/scala/whisk/core/controller/test/ConductorsApiTests.scala
  tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala
Labels: controller, pgapproved, review

#3309 Rework rule tests to not rely on views anymore.
  tests/src/test/scala/common/WskTestHelpers.scala
  tests/src/test/scala/system/basic/WskRuleTests.scala
  tests/src/test/scala/system/basic/WskSequenceTests.scala
Labels: alert, pgapproved, review

#3299 Remove two log messages, tweak logging with metrics, add log message for conductors
  common/scala/src/main/scala/whisk/common/TransactionId.scala
  core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
  core/controller/src/main/scala/whisk/core/controller/actions/SequenceActions.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
Labels: pgapproved, review

#3310 Refactor activation finisher without actor.
  core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala
  tests/src/test/scala/whisk/core/controller/actions/test/ActivationFinisherTests.scala
Labels: pgapproved, review

#3287 Fix view mismatch in test
  tests/src/test/scala/whisk/core/entity/test/ViewTests.scala
Labels: alert, pgapproved, review

#3219 Kubernetes ContainerFactoryProvider implementation
  common/scala/build.gradle
  common/scala/src/main/scala/whisk/common/Logging.scala
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  core/invoker/Dockerfile
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesClient.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainer.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
  tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerTests.scala
  tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesClientTests.scala
  tests/src/test/scala/whisk/core/containerpool/kubernetes/test/KubernetesContainerTests.scala
Labels: invoker, pgapproved, review

#3330 Update Log Store Fetch
  common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/DockerToActivationLogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/LogDriverLogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/LogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/SplunkLogStore.scala
  core/controller/src/main/scala/whisk/core/controller/Activations.scala
  tests/src/test/scala/whisk/core/containerpool/logging/SplunkLogStoreTests.scala
Labels: logging, review

#3331 Make package test resilient against eventual consistency.
  tests/src/test/scala/whisk/core/controller/test/PackagesApiTests.scala
Labels: alert, review

#3332 Add '-e' to redo for ansible variables and change '-a' to gradle arguments only.
  tools/build/redo
Labels: review

#3323 Normalize a missing body for raw actions to JsString.empty.
  core/controller/src/main/scala/whisk/core/controller/WebActions.scala
  tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala
Labels: controller, pgapproved, review

#3341 Remove view supporting now removed API for listing assets in namespace.
  ansible/files/whisks_design_document_for_all_entities_db_v2.1.0.json
  ansible/tasks/recreateViews.yml
Labels: pgapproved

#3333 Make parameters with defined values final
  common/scala/src/main/scala/whisk/core/entity/Parameter.scala
  core/controller/src/main/scala/whisk/core/controller/Actions.scala
  core/controller/src/main/scala/whisk/core/controller/WebActions.scala
  tests/src/test/scala/whisk/core/controller/test/ActionsApiTests.scala
Labels: pgapproved, review

#3318 Remove restriction on updating a trigger with a new feed.
  core/controller/src/main/scala/whisk/core/controller/Triggers.scala
  tests/src/test/scala/whisk/core/controller/test/TriggersApiTests.scala
Labels: controller, feedback, pgapproved, review

#3336 Remove dead field.
  tests/src/test/scala/common/WhiskProperties.java
Labels: companion, pgapproved

#3072 Enhance kafka message provider
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
  common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
  common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
  common/scala/src/main/scala/whisk/core/connector/MessageConsumer.scala
  common/scala/src/main/scala/whisk/core/connector/MessagingProvider.scala
  common/scala/src/main/scala/whisk/core/database/RemoteCacheInvalidation.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  tests/src/test/scala/ha/ShootComponentsTests.scala
  tests/src/test/scala/services/KafkaConnectorTests.scala
  tests/src/test/scala/whisk/core/connector/test/MessageFeedTests.scala
  tests/src/test/scala/whisk/core/connector/test/TestConnector.scala
Labels: kafka, pgapproved, review

#3215 adding namePrefix config to ContainerArgsConfig
  common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala
  common/scala/src/main/scala/whisk/core/entity/InstanceId.scala
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
  core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
Labels: review

#3347 Generic Pooling REST Client
  common/scala/src/main/scala/whisk/core/database/CloudantRestClient.scala
  common/scala/src/main/scala/whisk/core/database/CouchDbRestClient.scala
  common/scala/src/main/scala/whisk/http/PoolingRestClient.scala
  tests/src/test/scala/whisk/core/database/test/ExtendedCouchDbRestClient.scala
Labels: review

#3326 Make SplunkLogStore tests more resilient.
  tests/src/test/scala/whisk/core/containerpool/logging/SplunkLogStoreTests.scala
Labels: alert, review

#3335 Allow container tests to run without a proxy.
  ansible/README.md
  tests/src/test/scala/actionContainers/ActionContainer.scala
  tests/src/test/scala/actionContainers/DockerExampleContainerTests.scala
Labels: pgapproved

#3367 Narrow exclude to run needed tests.
  tests/build.gradle
Labels: review

#3368 Soften DockerExampleContainerTests.
  tests/src/test/scala/actionContainers/DockerExampleContainerTests.scala
Labels: review

#3357 Remove usages of replace and replaceAll on the hotpath.
  common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
Labels: performance, pgapproved, review
