Repository apache/openwhisk, pull requests merged in 2018-04, with the labels that each got.

#3459 Wrap producer.send with Future
  common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
Labels: kafka, review

#3422 Only join cluster if seed nodes are provided.
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
Labels: review

#3421 Add ElasticSearch Log Store
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchLogStore.scala
  common/scala/src/main/scala/whisk/core/containerpool/logging/ElasticSearchRestClient.scala
  common/scala/src/main/scala/whisk/http/PoolingRestClient.scala
  core/controller/src/main/scala/whisk/core/controller/ApiUtils.scala
  tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchLogStoreTests.scala
  tests/src/test/scala/whisk/core/containerpool/logging/ElasticSearchRestClientTests.scala
Labels: companion, controller, invoker, review

#3490 Move controller config to reference.conf
  core/controller/src/main/resources/application.conf
  core/controller/src/main/resources/reference.conf
Labels: deployment

#3512 wrap filed rev of BulkEntityResult using Option
  common/scala/src/main/scala/whisk/core/entity/DocInfo.scala
Labels: couchdb, pgapproved, reviewed

#3471 Fixes #3470 - Changed hardcoded timeouts for idle containers and pause grace to config entries
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
Labels: invoker, reviewed

#3413 Remove deprecated loadbalancer.
  core/controller/src/main/scala/whisk/core/loadBalancer/ContainerPoolBalancer.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/DistributedLoadBalancerData.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancer.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerData.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/LocalLoadBalancerData.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/SharedDataService.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/ContainerPoolBalancerObjectTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/LoadBalancerDataTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
  tests/src/test/scala/whisk/core/loadBalancer/test/SharedDataServiceTests.scala
Labels: blocked, loadbalancer, review

#3475 Move performance repository to core repository.
  performance/.travis.yml
  performance/README.md
  performance/preparation/create.sh
  performance/preparation/deploy.sh
  performance/wrk_tests/latency.sh
  performance/wrk_tests/post.lua
  performance/wrk_tests/throughput.sh
Labels: review

#3211 implement ContainerFactory.cpuShare to fix #3110
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/containerpool/ContainerFactory.scala
  common/scala/src/main/scala/whisk/core/mesos/MesosContainerFactory.scala
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
  core/invoker/src/main/scala/whisk/core/containerpool/docker/DockerContainerFactory.scala
  core/invoker/src/main/scala/whisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
  core/invoker/src/main/scala/whisk/core/invoker/Invoker.scala
  core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala
  tests/src/test/scala/common/LoggedFunction.scala
  tests/src/test/scala/whisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
  tests/src/test/scala/whisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerArgsConfigTest.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
Labels: awaits-feedback, review

#3526 Add gatling as performance test suite.
  .travis.yml
  performance/README.md
  performance/gatling_tests/build.gradle
  performance/gatling_tests/src/gatling/resources/conf/logback.xml
  performance/gatling_tests/src/gatling/scala/ApiV1Simulation.scala
  performance/gatling_tests/src/gatling/scala/extension/whisk/OpenWhiskActionBuilder.scala
  performance/gatling_tests/src/gatling/scala/extension/whisk/OpenWhiskDsl.scala
  performance/gatling_tests/src/gatling/scala/extension/whisk/OpenWhiskProtocolBuilder.scala
  performance/gatling_tests/src/gatling/scala/extension/whisk/Predef.scala
  performance/preparation/deploy.sh
  settings.gradle
Labels: review

#3547 Remove bookkeeping setting which is no longer applicable.
  ansible/roles/controller/tasks/deploy.yml
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  core/controller/src/main/scala/whisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  docs/deploy.md
Labels: loadbalancer, review

#3551 Bump timeout for creating a container to 60 seconds in tests.
  tests/src/test/scala/actionContainers/ActionContainer.scala
Labels: review, testing

#3495 Update akka to 2.5.12 and akka-http to 10.1.1.
  common/scala/build.gradle
  common/scala/src/main/scala/whisk/core/entity/ArgNormalizer.scala
  core/controller/build.gradle
  tests/build.gradle
  tests/src/test/scala/common/BaseWsk.scala
  tests/src/test/scala/common/rest/WskRest.scala
  tests/src/test/scala/system/basic/WskActionTests.scala
  tests/src/test/scala/system/basic/WskBasicSwift3Tests.scala
  tests/src/test/scala/system/basic/WskConductorTests.scala
  tests/src/test/scala/system/basic/WskConsoleTests.scala
  tests/src/test/scala/system/rest/ActionSchemaTests.scala
  tests/src/test/scala/system/rest/RestUtil.scala
  tests/src/test/scala/whisk/core/cli/test/Swift311Tests.scala
  tests/src/test/scala/whisk/core/connector/test/MessageFeedTests.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala
  tests/src/test/scala/whisk/core/database/test/CleanUpActivationsTest.scala
  tests/src/test/scala/whisk/core/entity/test/ActivationResponseTests.scala
Labels: pgapproved, review

#3556 Add latency test with gatling.
  .travis.yml
  performance/README.md
  performance/gatling_tests/build.gradle
  performance/gatling_tests/src/gatling/resources/data/javaAction.jar
  performance/gatling_tests/src/gatling/resources/data/javaAction.java
  performance/gatling_tests/src/gatling/resources/data/nodeJSAction.js
  performance/gatling_tests/src/gatling/resources/data/pythonAction.py
  performance/gatling_tests/src/gatling/resources/data/swiftAction.swift
  performance/gatling_tests/src/gatling/scala/LatencySimulation.scala
  performance/gatling_tests/src/gatling/scala/extension/whisk/OpenWhiskActionBuilder.scala
Labels: review

#3517 MemoryArtifactStore for unit testing and ArtifactStore SPI Validation
  common/scala/src/main/scala/whisk/core/database/ArtifactStoreExceptions.scala
  common/scala/src/main/scala/whisk/core/database/CouchDbRestStore.scala
  common/scala/src/main/scala/whisk/core/database/DocumentHandler.scala
  common/scala/src/main/scala/whisk/core/database/StoreUtils.scala
  common/scala/src/main/scala/whisk/core/database/memory/MemoryArtifactStore.scala
  common/scala/src/main/scala/whisk/core/database/memory/MemoryViewMapper.scala
  tests/src/test/scala/whisk/core/cli/test/SequenceMigrationTests.scala
  tests/src/test/scala/whisk/core/controller/test/ActivationsApiTests.scala
  tests/src/test/scala/whisk/core/database/CouchDBArtifactStoreTests.scala
  tests/src/test/scala/whisk/core/database/memory/MemoryArtifactStoreTests.scala
  tests/src/test/scala/whisk/core/database/test/DbUtils.scala
  tests/src/test/scala/whisk/core/database/test/DocumentHandlerTests.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreActivationsQueryBehaviors.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreBehavior.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreBehaviorBase.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreCRUDBehaviors.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreQueryBehaviors.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreSubjectQueryBehaviors.scala
  tests/src/test/scala/whisk/core/database/test/behavior/ArtifactStoreWhisksQueryBehaviors.scala
  tests/src/test/scala/whisk/core/invoker/test/NamespaceBlacklistTests.scala
Labels: artifactstore

#3546 Fix vagrant not use runc
  .gitattributes
  .gitignore
  ansible/environments/vagrant/group_vars/all
  ansible/environments/vagrant/hosts
  ansible/files/auth.guest
  ansible/files/auth.whisk.system
  tools/ubuntu-setup/docker-xenial.sh
  tools/ubuntu-setup/docker.sh
  tools/vagrant/README.md
  tools/vagrant/Vagrantfile
Labels: review

#3563 Skip log collection if the log-limit is set to "0".
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/whisk/core/WhiskConfig.scala
  common/scala/src/main/scala/whisk/core/entity/Limits.scala
  common/scala/src/main/scala/whisk/core/entity/LogLimit.scala
  core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala
  tests/src/test/scala/whisk/core/containerpool/test/ContainerProxyTests.scala
  tests/src/test/scala/whisk/core/entity/test/SchemaTests.scala
  tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala
Labels: review

#3554 Bump timeout of activation logs test.
  tests/src/test/scala/system/basic/WskActivationTests.scala
Labels: alert, review

#3571 Bump retries for view based tests.
  tests/src/test/scala/whisk/core/database/test/DbUtils.scala
  tests/src/test/scala/whisk/core/invoker/test/NamespaceBlacklistTests.scala
Labels: alert, review

#3427 Add Gatling tests to test performance.
  .travis.yml
  performance/README.md
  performance/gatling_tests/src/gatling/scala/BlockingInvokeOneActionSimulation.scala
Labels: review

#3581 Bump nginx version to latest and disable server-side information.
  ansible/group_vars/all
  ansible/roles/nginx/templates/nginx.conf.j2
Labels: deployment, nginx, review

#3325 Refactor Kafka clients for more generalized configuration reading.
  common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala
  common/scala/src/main/scala/whisk/connector/kafka/KafkaMessagingProvider.scala
  common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala
Labels: pgapproved, review

#3249 #3243 - Use gradle scoverage to collect test coverage stats
  build.gradle
  common/scala/build.gradle
  core/controller/build.gradle
  core/invoker/build.gradle
  settings.gradle
  tests/build.gradle
  tools/travis/build.sh
Labels: build, pgapproved, review, testing
