Repository apache/openwhisk, pull requests merged in 2019-09, with the labels that each got.

#4619 Add ansible deploy options
  ansible/roles/kafka/tasks/deploy.yml
  ansible/roles/zookeeper/tasks/deploy.yml
Labels: ready

#4611 Factor out subjects view name for identities
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBViewMapper.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/memory/MemoryViewMapper.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/GenericAuthKey.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/Identity.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskActivation.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskPackage.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskStore.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/InvokerSupervision.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/ElasticSearchLogStoreTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/SplunkLogStoreTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/test/DockerToActivationLogStoreTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/BasicAuthenticateTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/EntitlementProviderTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/WhiskAuthHelpers.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/ArtifactWithFileStorageActivationStoreTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/test/DbUtils.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreActivationsQueryBehaviors.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreQueryBehaviors.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreWhisksQueryBehaviors.scala
  tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/invoker/test/NamespaceBlacklistTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/InvokerSupervisionTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
  tools/admin/wskadmin
Labels: ready

#4617 Add kind "unknown" to fallback activations
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/Exec.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
Labels: ready

#4503 Add optional config for appending custom registry to user provided images
  ansible/group_vars/all
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/Exec.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/ExecManifest.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/mesos/MesosContainerFactory.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/yarn/YARNContainerFactory.scala
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainer.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainerFactory.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/StandaloneDockerContainerFactory.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
  tests/src/test/resources/application.conf.j2
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/yarn/test/YARNContainerFactoryTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecManifestTests.scala
Labels: enhancement, invoker

#4624 Combines active ack and slot release when both are available.
  common/scala/src/main/scala/org/apache/openwhisk/core/connector/Message.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/Exec.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/CommonLoadBalancer.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
  tests/src/test/scala/org/apache/openwhisk/core/connector/tests/AcknowledgementMessageTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: ready

#4640 Update to CosmosDB SDK v2.6.1
  common/scala/build.gradle
Labels: cosmosdb
