Repository apache/openwhisk, pull requests merged in 2019-02, with the labels that each got.

#4243 Optional write activation results to file…
  common/scala/src/main/scala/org/apache/openwhisk/core/database/ActivationFileStorage.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/ArtifactWithFileStorageActivationStore.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/ArtifactWithFileStorageActivationStoreTests.scala
Labels: review

#4256 Update docs to remove bluemix refs.
  docs/rest_api.md
Labels: documentation, review

#4258 Allow CLI download form /cli in addition to the longer /cli/go/download
  ansible/roles/nginx/templates/nginx.conf.j2
  docs/cli.md
Labels: ready

#4202 Bump ephemeral couchdb to v2.3
  ansible/group_vars/all
Labels: couchdb

#4254 Remove older runtimes
  ansible/files/runtimes.json
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/ExecManifest.scala
  core/controller/src/main/resources/apiv1swagger.json
  docs/actions-new.md
  docs/actions-nodejs.md
  docs/actions-php.md
  docs/actions-python.md
  docs/actions-swift.md
  tests/dat/actions/unicode.tests/php-7.1.txt
  tests/dat/actions/unicode.tests/php-7.2.txt
  tests/dat/actions/unicode.tests/swift-3.1.1.txt
  tests/dat/actions/unicode.tests/swift-4.1.txt
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackageActionsApiTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/migration/SequenceActionApiMigrationTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecHelpers.scala
  tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecManifestTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: runtime

#4261 Re-enable Swagger tests.
  tools/travis/runTests.sh
Labels: ready, testing

#4216 Proposing Lean OpenWhisk
  ansible/README.md
  ansible/group_vars/all
  ansible/openwhisk.yml
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/controller/tasks/lean.yml
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/scala/org/apache/openwhisk/connector/lean/LeanConsumer.scala
  common/scala/src/main/scala/org/apache/openwhisk/connector/lean/LeanMessagingProvider.scala
  common/scala/src/main/scala/org/apache/openwhisk/connector/lean/LeanProducer.scala
  core/controller/Dockerfile
  core/controller/build.gradle
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/CommonLoadBalancer.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LeanBalancer.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LoadBalancer.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  tests/build.gradle
  tests/performance/preparation/deploy-lean.sh
  tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
  tools/travis/runLeanSystemTests.sh
  tools/travis/setupLeanSystem.sh
  tools/vagrant/README.md
  tools/vagrant/Vagrantfile
Labels: companion, controller, invoker, loadbalancer, pgapproved

#4205 Use redis-cli (via docker) to test status of Redis in ansible PING-PONG
  ansible/roles/redis/tasks/deploy.yml
Labels: ready

#4168 Remove unused ansible parameters in group_vars/all file.
  ansible/group_vars/all
  ansible/roles/nginx/tasks/deploy.yml
Labels: ansible, ready

#4259 Mount an optional html directory for serving static content.
  ansible/group_vars/all
  ansible/roles/nginx/tasks/deploy.yml
  ansible/roles/nginx/templates/nginx.conf.j2
Labels: awaits-reviewer, deployment, enhancement

#4229 Add support for TTL at collection level with CosmosDB
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreProvider.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfig.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBSupport.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfigTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBSupportTests.scala
Labels: artifactstore, awaits-contributor

#4186 Track activation counts in ContainerPool (not ContainerProxy)
  common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/Container.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerPoolTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/limits/ConcurrencyTests.scala
Labels: invoker, pgapproved, review

#4262 Create _users database only if it does not already exist.
  ansible/roles/couchdb/tasks/deploy.yml
Labels: couchdb, review

#4250 Allow persisted couchdb directory mount.
  ansible/group_vars/all
  ansible/roles/couchdb/tasks/deploy.yml
Labels: couchdb, review

#4249 Add revoke key feature to wskadmin
  tools/admin/wskadmin
Labels: review, tooling

#4227 Enable publishing metrics to Prometheus
  ansible/roles/nginx/templates/nginx.conf.j2
  common/scala/build.gradle
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
  common/scala/src/main/scala/org/apache/openwhisk/common/Prometheus.scala
  common/scala/src/main/scala/org/apache/openwhisk/common/TransactionId.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
  common/scala/src/main/scala/org/apache/openwhisk/http/BasicHttpService.scala
  common/scala/src/main/scala/org/apache/openwhisk/http/BasicRasService.scala
  tests/src/test/scala/org/apache/openwhisk/common/PrometheusTests.scala
Labels: companion, deployment, metrics, ready

#4253 Remove deadcode.
  ansible/templates/whisk.properties.j2
  tests/src/test/scala/common/WhiskProperties.java
  tests/src/test/scala/common/WskCliOperations.scala
Labels: review

#4267 Remove ansible warnings and use unarchive task
  ansible/roles/cli/tasks/deploy.yml
  ansible/roles/controller/tasks/deploy.yml
  ansible/roles/invoker/tasks/deploy.yml
Labels: ansible, review

#4278 Add additional debug information for intermittently failing ContainerProxyTests
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
Labels: review

#4279 Fix typos in docs
  ansible/README.md
  docs/about.md
  docs/actions-docker.md
  docs/actions-nodejs.md
  docs/actions-swift.md
  docs/actions.md
  docs/catalog.md
  docs/cli.md
  docs/deploy.md
  docs/mesos.md
  docs/metrics.md
  docs/mobile_sdk.md
  docs/parameters.md
  docs/reference.md
  docs/spi.md
  tests/performance/README.md
  tools/admin/README-NEXT.md
  tools/build/README.md
  tools/db/README.md
  tools/dev/README.md
  tools/macos/README.md
  tools/macos/docker-machine/README.md
  tools/ubuntu-setup/README.md
  tools/vagrant/README.md
Labels: documentation, ready

#4276 Scalatest version update
  tests/build.gradle
Labels: review, testing

#4271 package nodejs dependencies into routemgmt actions
  ansible/roles/routemgmt/files/installRouteMgmt.sh
  core/routemgmt/createApi/package.json
  core/routemgmt/deleteApi/package.json
  core/routemgmt/getApi/package.json
Labels: apigw, review

#4289 Make ContainerProxyTests more stable.
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
Labels: heisenbug, review, testing

#4287 Disable test failing with CosmosDB v2.4.0
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreTests.scala
Labels: cosmosdb

#4280 MBean to dump config information at a path
  common/scala/src/main/scala/org/apache/openwhisk/common/ConfigMXBean.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/Controller.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
  tests/src/test/scala/org/apache/openwhisk/common/ConfigMXBeanTests.scala
Labels: logging

#4031 Add common test codes for ActivationStore
  tests/src/test/scala/org/apache/openwhisk/core/database/ArtifactActivationStoreBehaviorBase.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/ArtifactActivationStoreTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ActivationStoreBehavior.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ActivationStoreBehaviorBase.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ActivationStoreCRUDBehaviors.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ActivationStoreQueryBehaviors.scala
Labels: artifactstore, review

#4291 Changing Catalog installation to use whisk deploy
  ansible/tasks/installOpenwhiskCatalog.yml
Labels: deployment, reviewed

#4294 Multiple fixes to apiv1swagger.json
  core/controller/src/main/resources/apiv1swagger.json
Labels: reviewed, swagger

#4255 Improve container factory documentation
  common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
Labels: awaits-contributor, documentation, review

#4129 Adding YARNContainerFactory. This allows OpenWhisk to run actions on Apache Hadoop clusters.
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/yarn/YARNComponentActor.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/yarn/YARNContainerFactory.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/yarn/YARNContainerInfoActor.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/yarn/YARNRESTUtil.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/yarn/YARNTask.scala
  docs/yarn.md
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/yarn/test/MockYARNRM.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/yarn/test/YARNContainerFactoryTests.scala
Labels: enhancement, invoker, reviewed

#4273 Enable configuring Connection Mode for CosmosDB
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfig.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfigTests.scala
Labels: review

#4305 Use runtime tags specified in runtime manifest for YARNContainerFactoryTests
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/yarn/test/YARNContainerFactoryTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecHelpers.scala
Labels: review

#4307 Use custom runtime manifest for YARN tests
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/yarn/test/YARNContainerFactoryTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/entity/test/ExecHelpers.scala
Labels: review

#4263 Add description for new metrics added
  docs/metrics.md
Labels: documentation, metrics, review

#4299 Avoid that actions do not stop after action timeout when logging heavily
  common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/logging/DockerToActivationFileLogStore.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/logging/DockerToActivationLogStore.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskActivation.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
  tests/dat/actions/loggingTimeout.js
  tests/src/test/scala/common/TimingHelpers.scala
  tests/src/test/scala/org/apache/openwhisk/core/limits/ActionLimitsTests.scala
Labels: bug, invoker, review

#4313 Restore default runtimes after YARN tests finish
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/yarn/test/YARNContainerFactoryTests.scala
Labels: review
