Repository apache/openwhisk, pull requests merged in 2019-01, with the labels that each got.

#4156 Make exec aka code max size configurable
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/Exec.scala
  docs/reference.md
Labels: controller, enhancement, review

#4151 Route Gatling failure logs to file
  ansible/logs.yml
  tests/performance/gatling_tests/src/gatling/resources/conf/logback.xml
Labels: review

#4165 Update to Kamon 1.1.3 from 0.6 series
  common/scala/build.gradle
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/Controller.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
Labels: review

#4088 Make activation polling for blocking invocations configurable
  ansible/roles/controller/tasks/deploy.yml
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/PrimitiveActions.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
Labels: controller, enhancement, review

#4176 additional container factory dns configuration
  common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerClient.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainer.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainerFactory.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerClientTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerClientWithFileAccessTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerArgsConfigTest.scala
Labels: invoker, pgapproved

#4214 Avoid Database Replicator Failures
  tests/src/test/scala/org/apache/openwhisk/core/database/test/ReplicatorTests.scala
Labels: review

#4185 recreate http client on resume()
  common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/Container.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/mesos/MesosTask.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainer.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainer.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/logging/test/DockerToActivationLogStoreTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
Labels: invoker, review, reviewed

#4220 Make fraction of managed invokers configurable.
  ansible/group_vars/all
  ansible/roles/controller/tasks/deploy.yml
  core/controller/src/main/resources/reference.conf
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
  tests/src/test/scala/org/apache/openwhisk/core/loadBalancer/test/ShardingContainerPoolBalancerTests.scala
Labels: review

#3991 Provide Artifact with File Storage Activation Store
  common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/ActivationFileStorage.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/ArtifactWithFileStorageActivationStore.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskActivation.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/Activations.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActivationsApiTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/ControllerTestCommon.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/ArtifactWithFileStorageActivationStoreTests.scala
Labels: awaits-reviewer, review

#4239 Add Ballerina 0.990.2 runtime.
  ansible/files/runtimes.json
  core/controller/src/main/resources/apiv1swagger.json
  docs/actions-ballerina.md
  docs/actions-new.md
  docs/actions.md
  tests/dat/actions/unicode.tests/ballerina-0.990.bin
  tests/dat/actions/unicode.tests/src/ballerina/unicode.bal
Labels: enhancement, review, runtime
