Repository apache/openwhisk, pull requests merged in 2019-03, with the labels that each got.

#4317 Make WskRestRuleTests more stable.
  tests/src/test/scala/system/basic/WskRestRuleTests.scala
Labels: review

#4312 Record clusterId performing change in CosmosDB
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfig.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBUtil.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfigTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBStoreBehaviorBase.scala
Labels: cosmosdb

#4321 Update CosmosDB to 2.4.2
  common/scala/build.gradle
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
  tests/src/test/resources/application.conf.j2
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreAttachmentBehaviors.scala
Labels: cosmosdb

#4284 Add an annotations to inject the API key into the action context.
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/Parameter.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskAction.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
  docs/actions.md
  docs/annotations.md
  tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestBasicUsageTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/ControllerTestCommon.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/PackageActionsApiTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/entity/test/SchemaTests.scala
  tests/src/test/scala/system/basic/WskActionTests.scala
  tests/src/test/scala/system/basic/WskRestBasicTests.scala
Labels: controller, ready, security

#4328 Set API key annotation for a WskConsole test
  tests/src/test/scala/system/basic/WskConsoleTests.scala
Labels: review

#4327 Use Gauge metric instead of Histogram where applicable
  common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
  common/scala/src/main/scala/org/apache/openwhisk/connector/kafka/KafkaConsumerConnector.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/CommonLoadBalancer.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LeanBalancer.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/ShardingContainerPoolBalancer.scala
Labels: metrics, review

#4346 Adapts test harness to parses activation ids from wsk activation list with new format.
  tests/src/test/scala/common/WskCliOperations.scala
Labels: pgapproved, review, testing

#4340 Fix intermittent test failure related to sequence execution error propagation
  tests/src/test/scala/system/basic/WskSequenceTests.scala
Labels: review

#4329 Redirect http to https and other nginx config cleanup.
  ansible/group_vars/all
  ansible/roles/nginx/tasks/deploy.yml
  ansible/roles/nginx/templates/nginx.conf.j2
  ansible/setup.yml
Labels: deployment, pgapproved, review

#4345 Initial commit to add the deployment configuration for Jenkins
  ansible/environments/jenkins/ansible_jenkins.cfg
  ansible/environments/jenkins/group_vars/all
  ansible/environments/jenkins/hosts.j2.ini
  ansible/setup.yml
  tools/jenkins/Jenkinsfile
Labels: tooling

#4343 Move runtimesRegistry to pureconfig.
  ansible/roles/invoker/tasks/deploy.yml
  common/scala/src/main/scala/org/apache/openwhisk/core/WhiskConfig.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerFactory.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/mesos/MesosContainerFactory.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/loadBalancer/LeanBalancer.scala
  core/invoker/src/main/resources/application.conf
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainerFactory.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainerFactory.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
  tests/src/test/resources/application.conf.j2
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/docker/test/DockerContainerFactoryTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/mesos/test/MesosContainerFactoryTest.scala
Labels: review

#4356 Add the private docker registry for three VMs under Apache
  ansible/environments/jenkins/group_vars/all
  tools/jenkins/Jenkinsfile
Labels: jenkins

#4360 Add the file Jenkinsfile into the root directory of OpenWhisk
  Jenkinsfile
Labels: jenkins

#4339 Enable soft delete mode for documents in CosmosDB
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfig.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBUtil.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBViewMapper.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBSoftDeleteTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBStoreBehaviorBase.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreCRUDBehaviors.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/test/behavior/ArtifactStoreQueryBehaviors.scala
Labels: cosmosdb

#4351 Add gauge metrics to docs
  docs/metrics.md
Labels: documentation, review

#4388 Adapt limit to query db view as per couch db change
  core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/NamespaceBlacklist.scala
Labels: couchdb, review

#4391 Improve the efficiency of Jenkins pipeline
  Jenkinsfile
  ansible/environments/jenkins/group_vars/openwhisk-vm1-he-de
  ansible/environments/jenkins/group_vars/openwhisk-vm2-he-de
  ansible/environments/jenkins/group_vars/openwhisk-vm3-he-de
  ansible/environments/jenkins/openwhisk-vm1-he-de.j2.ini
  ansible/environments/jenkins/openwhisk-vm2-he-de.j2.ini
  ansible/environments/jenkins/openwhisk-vm3-he-de.j2.ini
Labels: jenkins

#4384 Update the OpenWhisk module list
  docs/dev/modules.md
  tools/dev/src/main/groovy/CategoryManager.groovy
Labels: documentation

#4404 Fix the test report issue, so all the test result is posted
  Jenkinsfile
  tests/build.gradle
  tests/src/test/scala/invokerShoot/ShootInvokerTests.scala
Labels: jenkins
