Repository apache/openwhisk, pull requests merged in 2019-05, with the labels that each got.

#4453 Add SPI for invoker
  common/scala/src/main/resources/reference.conf
  core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/Invoker.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala
Labels: pgapproved

#4446 Actionloop docs
  README.md
  docs/actions-actionloop.md
  docs/actions.md
Labels: documentation, review

#4469 Touch-up Action loop markdown adjusting grammar/flow
  docs/actions-actionloop.md
Labels: documentation, review

#4295 Honor skip and limit aparameters in action /whisk.system/apimgmt/getA…
  core/routemgmt/common/apigw-utils.js
  core/routemgmt/getApi/getApi.js
Labels: apigw, review

#4325 Adjust error handling in the Cloudant Rest Store
  common/scala/src/main/scala/org/apache/openwhisk/core/database/ArtifactStoreExceptions.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/CouchDbRestStore.scala
Labels: logging, ready

#4211 Add `binding` annotation to record an action path not resolved
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/FullyQualifiedEntityName.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskAction.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskActivation.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/PrimitiveActions.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/SequenceActions.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
  docs/annotations.md
  tests/src/test/scala/system/basic/WskConductorTests.scala
  tests/src/test/scala/system/basic/WskPackageTests.scala
  tests/src/test/scala/system/basic/WskSequenceTests.scala
Labels: controller, enhancement, review

#4475 Additional cleanup and simplifications for the ActionLoop docs
  docs/actions-actionloop.md
Labels: documentation, enhancement, wip

#4484 Switch to consistent indexing policy for CosmosDB
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBSupport.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBViewMapper.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/IndexingPolicy.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/IndexingPolicyTests.scala
Labels: cosmosdb

#4490 Track collection usage metrics for CosmosDB
  common/scala/src/main/resources/application.conf
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CollectionResourceUsage.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStore.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBConfig.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CollectionResourceUsageTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/cosmosdb/CosmosDBArtifactStoreTests.scala
Labels: cosmosdb
