Repository apache/openwhisk, pull requests merged in 2019-04, with the labels that each got.

#4320 Added owperf, a performance evaluation tool for OpenWhisk, under tools
  tools/owperf/README.md
  tools/owperf/owperf.js
  tools/owperf/owperf.sh
  tools/owperf/owperf_data.odg
  tools/owperf/owperf_data.png
  tools/owperf/package.json
  tools/owperf/setup.sh
  tools/owperf/testAction.js
Labels: performance, review, tooling

#4290 Enable couchdb persist_path in a distributed environment as well
  ansible/roles/couchdb/tasks/deploy.yml
Labels: couchdb, reviewed

#4407 Use static metric names when tag support is enabled
  common/scala/src/main/scala/org/apache/openwhisk/common/Logging.scala
Labels: metrics, ready

#4392 Enable attachment reads from CloudFront
  common/scala/build.gradle
  common/scala/src/main/resources/s3-reference.conf
  common/scala/src/main/scala/org/apache/openwhisk/core/database/s3/CloudFrontSigner.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/database/s3/S3AttachmentStore.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/s3/CloudFrontSignerTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/s3/S3AttachmentStoreCloudFrontTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/s3/S3Aws.scala
  tests/src/test/scala/org/apache/openwhisk/core/database/test/AttachmentStoreBehaviors.scala
Labels: s3

#4457 make wskadmin python2 and python3 compatible
  tools/admin/wskadmin
Labels: ready
