Repository apache/openwhisk, pull requests merged in 2019-06, with the labels that each got.

#4505 Fix a few compilation accidents
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/Exec.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/ExecManifest.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskActivation.scala
  common/scala/src/main/scala/org/apache/openwhisk/http/ErrorResponse.scala
Labels: ready

#4499 #3401: Moved local variables to Constants and renamed all occurences
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/Annotations.scala
  common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskAction.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/Actions.scala
  core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala
  core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala
  tests/src/test/scala/invokerShoot/ShootInvokerTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/cli/test/WskRestBasicUsageTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/containerpool/test/ContainerProxyTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/ActionsApiTests.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/ControllerTestCommon.scala
  tests/src/test/scala/org/apache/openwhisk/core/controller/test/WebActionsApiTests.scala
  tests/src/test/scala/system/basic/WskActionTests.scala
  tests/src/test/scala/system/basic/WskConsoleTests.scala
  tests/src/test/scala/system/basic/WskRestBasicTests.scala
Labels: enhancement, ready

#4517 Update Dockerfiles to full ASF license header
  ansible/environments/docker-machine/group_vars/all
  ansible/environments/jenkins/group_vars/openwhisk-vm1-he-de
  ansible/environments/jenkins/group_vars/openwhisk-vm2-he-de
  ansible/environments/jenkins/group_vars/openwhisk-vm3-he-de
  ansible/environments/local/group_vars/all
  ansible/environments/vagrant/group_vars/all
  ansible/group_vars/all
  common/scala/Dockerfile
  core/controller/Dockerfile
  core/controller/Dockerfile.cov
  core/invoker/Dockerfile
  core/invoker/Dockerfile.cov
  tools/actionProxy/Dockerfile
  tools/ow-utils/Dockerfile
Labels: compliance, wip
